#! /bin/bash
cd "$(dirname "$0")" # go to script folder

if [ "$#" -lt 1 ]; then
    echo "Please supply name of person as arguments"
    exit 1
fi

echo -n $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)" " >> tokens
echo $@ >> tokens

echo "Generated:"
tail -n1 tokens

